### ISSUE TITLE
import fails on Python 2

### ISSUE THREAD

**Issue by xflr6** [wikier/keepalive#1]
```python
>>> import keepalive
Traceback (most recent call last):
(...)
    import urllib.request, urllib.error, urllib.parse
ImportError: No module named request
```
see http://python3porting.com/stdlib.html#urllib-urllib2-and-urlparse, also makes [this](https://github.com/RDFLib/sparqlwrapper/blob/920578508b1ab19a99db60b936c57cfc427b5041/SPARQLWrapper/Wrapper.py#L402-L408) ineffective

**Comment by wikier** [comment]
Strictly this is a Python 3 module, but the package classifiers were wrong.

Another issue is how to solve the `SPARQLWrapper` problem, see RDFLib/SPARQLWrapper#65 for further investigations.
